on: push

jobs:
  push:
    if: github.ref != 'refs/heads/template'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - run: pip3 install -r .github/requirements.txt
    - run: .github/release.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
